export const chartData = [
  {
    title: "A pie chart showing ration of man per state",
    description: "A pie chart showing ration of man per state",
    result: {},
    totalCount: 0,
    chartType: "PIE",
    status: true,
  },
  {
    title: "A pie chart showing ration of men per state",
    description: "A pie chart showing ration of men per state",
    result: {},
    totalCount: 0,
    chartType: "BAR",
    status: false,
  },
  {
    title: "Barchart for primary DIAGNOSIS OF TYPE Type 2 Diabetes Mellitus",
    description:
      "Barchart for primary DIAGNOSIS OF TYPE Type 2 Diabetes Mellitus",
    result: {
      Abuja: {
        Active: 2,
        Completed: 1,
        Pending: 3,
      },
      Anambra: {
        Active: 1,
        Completed: 0,
        Pending: 1,
      },
      Kano: {
        Active: 1,
        Completed: 0,
        Pending: 0,
      },
      Lagos: {
        Active: 1,
        Completed: 0,
        Pending: 1,
      },
    },
    totalCount: 11,
    chartType: "INVERSED",
    status: false,
  },
  {
    title: "Barchart for primary DIAGNOSIS OF TYPE Type 2 Diabetes Mellitus",
    description:
      "Barchart for primary DIAGNOSIS OF TYPE Type 2 Diabetes Mellitus",
    result: {
      Abuja: {
        Active: 2,
        Completed: 1,
        Pending: 3,
      },
      Anambra: {
        Active: 1,
        Completed: 0,
        Pending: 1,
      },
      Kano: {
        Active: 1,
        Completed: 0,
        Pending: 0,
      },
      Lagos: {
        Active: 1,
        Completed: 0,
        Pending: 1,
      },
    },
    totalCount: 11,
    chartType: "BAR",
    status: false,
  },
  {
    title: "Barchart for primary DIAGNOSIS OF TYPE Type 2 Diabetes Mellitus",
    description:
      "Barchart for primary DIAGNOSIS OF TYPE Type 2 Diabetes Mellitus",
    result: {},
    totalCount: 0,
    chartType: "BAR",
    status: false,
  },
  {
    title: "Chart showing survey of Type 2 Diabetes Mellitus within Nigeria",
    description: "Type 2 Diabetes diagnosis",
    result: {
      Abuja: {
        Active: 2,
        Completed: 1,
        Pending: 3,
      },
      Anambra: {
        Active: 1,
        Completed: 0,
        Pending: 1,
      },
      Kano: {
        Active: 1,
        Completed: 0,
        Pending: 0,
      },
      Lagos: {
        Active: 1,
        Completed: 0,
        Pending: 1,
      },
    },
    totalCount: 11,
    chartType: "PIE",
    status: false,
  },
  {
    title: "Genoty chart",
    description: "Chart for genotype",
    result: {
      Abuja: {
        "A+": 1,
        "AB+": 0,
        "O+": 0,
        "B-": 0,
        "B+": 0,
        "A-": 0,
        "AB-": 0,
        "O-": 0,
      },
      Kano: {
        "A+": 0,
        "AB+": 0,
        "O+": 0,
        "B-": 0,
        "B+": 0,
        "A-": 0,
        "AB-": 0,
        "O-": 0,
      },
      Lagos: {
        "A+": 0,
        "AB+": 2,
        "O+": 1,
        "B-": 0,
        "B+": 1,
        "A-": 0,
        "AB-": 0,
        "O-": 0,
      },
    },
    totalCount: 5,
    chartType: "PIE",
    status: false,
  },
  {
    title: "Age rane chart for all states",
    description: "Nothing really",
    result: {},
    totalCount: 0,
    chartType: "BAR",
    status: false,
  },
  {
    title: "Stacked bar chart representation",
    description: "Check it",
    result: {},
    totalCount: 0,
    chartType: "STACKED",
    status: false,
  },
  {
    title: "Stacked bar chart representation",
    description: "Check it",
    result: {},
    totalCount: 0,
    chartType: "STACKED",
    status: false,
  },
  {
    title: "Genotype chart representation",
    description: "GEnotype",
    result: {
      Abuja: {
        AA: 0,
        AS: 0,
        SS: 0,
      },
      Anambra: {
        AA: 0,
        AS: 0,
        SS: 0,
      },
      Kano: {
        AA: 0,
        AS: 0,
        SS: 0,
      },
      Lagos: {
        AA: 1,
        AS: 2,
        SS: 0,
      },
    },
    totalCount: 3,
    chartType: "PIE",
    status: false,
  },
  {
    title: "Genotype chart representation",
    description: "GEnotype",
    result: {
      Abuja: {
        AA: 0,
        AS: 0,
        SS: 0,
      },
      Anambra: {
        AA: 0,
        AS: 0,
        SS: 0,
      },
      Kano: {
        AA: 0,
        AS: 0,
        SS: 0,
      },
      Lagos: {
        AA: 1,
        AS: 2,
        SS: 0,
      },
    },
    totalCount: 3,
    chartType: "PIE",
    status: false,
  },
  {
    title: "Medication chart",
    description: "med",
    result: {
      Abuja: {
        Amoxicillin: 3,
        Cinnarizine: 1,
        Felodipine: 0,
        Fentanyl: 0,
        Memantine: 0,
      },
      Anambra: {
        Amoxicillin: 1,
        Cinnarizine: 0,
        Felodipine: 0,
        Fentanyl: 0,
        Memantine: 0,
      },
      Kano: {
        Amoxicillin: 0,
        Cinnarizine: 0,
        Felodipine: 0,
        Fentanyl: 0,
        Memantine: 0,
      },
      Lagos: {
        Amoxicillin: 0,
        Cinnarizine: 0,
        Felodipine: 1,
        Fentanyl: 3,
        Memantine: 1,
      },
    },
    totalCount: 10,
    chartType: "PIE",
    status: false,
  },
  {
    title: "Immunization chart",
    description: "lonza etc.",
    result: {
      Abuja: {
        Lonza: 0,
        Pfizer: 0,
        Sanofi: 0,
        Moderna: 0,
        Sinovac: 0,
      },
      Anambra: {
        Lonza: 0,
        Pfizer: 0,
        Sanofi: 0,
        Moderna: 0,
        Sinovac: 0,
      },
      Kano: {
        Lonza: 0,
        Pfizer: 0,
        Sanofi: 0,
        Moderna: 0,
        Sinovac: 0,
      },
      Lagos: {
        Lonza: 0,
        Pfizer: 0,
        Sanofi: 0,
        Moderna: 0,
        Sinovac: 0,
      },
    },
    totalCount: 0,
    chartType: "BAR",
    status: false,
  },
];
